theme: jekyll-theme-cayman
title: [Плагин СДЭК для wordpress woocommerce]
description: [Калькулятор стоимости доставки курьерской службой СДЭК]
show_downloads: ["true"]
google_analytics: [UA-21586186-3]
